### PR TITLE
TACO-2822: Add support for micro mode

### PR DESCRIPTION
**Pull request by tyler-stocksdale**

### CODE REVIEW

**Review by corclark — APPROVED** [review]

**Comment by mattgraham1** [comment]
@corclark You should probably remove me from this repository. ;) Hope all is good with the teams.

**Comment by corclark** [comment]
> @corclark You should probably remove me from this repository. ;) Hope all is good with the teams.

@mattgraham1 haha I guess this was set up as a public repo. I didn't notice that until now!

**Comment by jeanhall** [comment]
> > @corclark You should probably remove me from this repository. ;) Hope all is good with the teams.
> 
> @mattgraham1 haha I guess this was set up as a public repo. I didn't notice that until now!

Yes this is a public repo. The idea originally was to commercialize the backend and make this SDK publicly available for third party companies to integrate their own apps with - like Specialized did before they bought the backend.

**Comment by jeanhall** [comment]
What do you want to do with this PR @tyler-stocksdale? Are we closing it or going ahead with it? If going ahead, can you undo the actions and pom changes?

**Comment by tyler-stocksdale** [comment]
> What do you want to do with this PR @tyler-stocksdale? Are we closing it or going ahead with it? If going ahead, can you undo the actions and pom changes?

@jeanhall I'm leaning towards closing it, but I want to make sure my alternative solution works first.

**Pull request closed without merging**
